// Code generated by Kitex v0.4.4. DO NOT EDIT.

package messageservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	message "github.com/edufriendchen/light-tiktok/kitex_gen/message"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ChatMessage(ctx context.Context, req *message.ChatRequest, callOptions ...callopt.Option) (r *message.ChatResponse, err error)
	ActionMessage(ctx context.Context, req *message.ActionRequest, callOptions ...callopt.Option) (r *message.ActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) ChatMessage(ctx context.Context, req *message.ChatRequest, callOptions ...callopt.Option) (r *message.ChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChatMessage(ctx, req)
}

func (p *kMessageServiceClient) ActionMessage(ctx context.Context, req *message.ActionRequest, callOptions ...callopt.Option) (r *message.ActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ActionMessage(ctx, req)
}
