// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/edufriendchen/light-tiktok/cmd/api/biz/handler"
	
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	root := r.Group("/douyin")

		{
			_user := root.Group("/user")
			_user.GET("/",  handler.MGetUserInfo)
			_user.POST("/login/",  handler.Login)
			_user.POST("/register/", handler.Register)
		}

		{
			_relation := root.Group("/relation")
			_relation.POST("/action/",  handler.RelationAction)
			_relation.GET("/follow/list",  handler.MGetFollowList)
			_relation.GET("/follower/list", handler.MGetFollowerList)
			_relation.GET("/friend/list", handler.MGetFriendList)
		}

		{
			_relation := root.Group("/message")
			_relation.POST("/action/",  handler.ActionMessage)
			_relation.GET("/chat/",  handler.MGetMessageList)
		}


		{
			_relation := root.Group("/publish")
			_relation.POST("/action/",  handler.PublishAction)
			_relation.GET("/list",  handler.MGetPublishList)
		}


		{
			_relation := root.Group("/feed")
			_relation.GET("/",  handler.MGetFeedList)
		}

		{
			_relation := root.Group("/favorite")
			_relation.POST("/action/",  handler.ActionFavorite)
			_relation.GET("/list",  handler.MGetFavoriteList)
		}

		{
			_relation := root.Group("/comment")
			_relation.POST("/action/",  handler.ActionComment)
			_relation.GET("/list",  handler.MGetCommentList)
		}
		
}
