// Code generated by Kitex v0.4.4. DO NOT EDIT.

package relationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	relation "github.com/edufriendchen/light-tiktok/kitex_gen/relation"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ActionRelation(ctx context.Context, req *relation.ActionRequest, callOptions ...callopt.Option) (r *relation.ActionResponse, err error)
	MGetFollowList(ctx context.Context, req *relation.FollowRequest, callOptions ...callopt.Option) (r *relation.FollowResponse, err error)
	MGetFollowerList(ctx context.Context, req *relation.FollowerRequest, callOptions ...callopt.Option) (r *relation.FollowerResponse, err error)
	MGetFriendList(ctx context.Context, req *relation.FriendRequest, callOptions ...callopt.Option) (r *relation.FriendResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRelationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRelationServiceClient struct {
	*kClient
}

func (p *kRelationServiceClient) ActionRelation(ctx context.Context, req *relation.ActionRequest, callOptions ...callopt.Option) (r *relation.ActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ActionRelation(ctx, req)
}

func (p *kRelationServiceClient) MGetFollowList(ctx context.Context, req *relation.FollowRequest, callOptions ...callopt.Option) (r *relation.FollowResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MGetFollowList(ctx, req)
}

func (p *kRelationServiceClient) MGetFollowerList(ctx context.Context, req *relation.FollowerRequest, callOptions ...callopt.Option) (r *relation.FollowerResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MGetFollowerList(ctx, req)
}

func (p *kRelationServiceClient) MGetFriendList(ctx context.Context, req *relation.FriendRequest, callOptions ...callopt.Option) (r *relation.FriendResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MGetFriendList(ctx, req)
}
