// Code generated by Validator v0.1.4. DO NOT EDIT.

package relation

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *ActionRequest) IsValid() error {
	if len(p.Token) < int(1) {
		return fmt.Errorf("field Token min_len rule failed, current value: %d", len(p.Token))
	}
	_src := []int8{int8(1), int8(2)}
	var _exist bool
	for _, src := range _src {
		if p.ActionType == int8(src) {
			_exist = true
			break
		}
	}
	if !_exist {
		return fmt.Errorf("field ActionType in rule failed, current value: %v", p.ActionType)
	}
	return nil
}
func (p *ActionResponse) IsValid() error {
	return nil
}
func (p *FollowRequest) IsValid() error {
	return nil
}
func (p *FollowResponse) IsValid() error {
	return nil
}
func (p *FollowerRequest) IsValid() error {
	return nil
}
func (p *FollowerResponse) IsValid() error {
	return nil
}
func (p *FriendRequest) IsValid() error {
	return nil
}
func (p *FriendResponse) IsValid() error {
	return nil
}
