// Code generated by Kitex v0.4.4. DO NOT EDIT.

package favoriteservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	favorite "github.com/edufriendchen/light-tiktok/kitex_gen/favorite"
)

func serviceInfo() *kitex.ServiceInfo {
	return favoriteServiceServiceInfo
}

var favoriteServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FavoriteService"
	handlerType := (*favorite.FavoriteService)(nil)
	methods := map[string]kitex.MethodInfo{
		"ActionFavorite":   kitex.NewMethodInfo(actionFavoriteHandler, newFavoriteServiceActionFavoriteArgs, newFavoriteServiceActionFavoriteResult, false),
		"MGetFavoriteList": kitex.NewMethodInfo(mGetFavoriteListHandler, newFavoriteServiceMGetFavoriteListArgs, newFavoriteServiceMGetFavoriteListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "favorite",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func actionFavoriteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceActionFavoriteArgs)
	realResult := result.(*favorite.FavoriteServiceActionFavoriteResult)
	success, err := handler.(favorite.FavoriteService).ActionFavorite(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceActionFavoriteArgs() interface{} {
	return favorite.NewFavoriteServiceActionFavoriteArgs()
}

func newFavoriteServiceActionFavoriteResult() interface{} {
	return favorite.NewFavoriteServiceActionFavoriteResult()
}

func mGetFavoriteListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceMGetFavoriteListArgs)
	realResult := result.(*favorite.FavoriteServiceMGetFavoriteListResult)
	success, err := handler.(favorite.FavoriteService).MGetFavoriteList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceMGetFavoriteListArgs() interface{} {
	return favorite.NewFavoriteServiceMGetFavoriteListArgs()
}

func newFavoriteServiceMGetFavoriteListResult() interface{} {
	return favorite.NewFavoriteServiceMGetFavoriteListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ActionFavorite(ctx context.Context, req *favorite.ActionRequest) (r *favorite.ActionResponse, err error) {
	var _args favorite.FavoriteServiceActionFavoriteArgs
	_args.Req = req
	var _result favorite.FavoriteServiceActionFavoriteResult
	if err = p.c.Call(ctx, "ActionFavorite", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MGetFavoriteList(ctx context.Context, req *favorite.FavoriteRequest) (r *favorite.FavoriteResponse, err error) {
	var _args favorite.FavoriteServiceMGetFavoriteListArgs
	_args.Req = req
	var _result favorite.FavoriteServiceMGetFavoriteListResult
	if err = p.c.Call(ctx, "MGetFavoriteList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
