// Code generated by Kitex v0.4.4. DO NOT EDIT.

package commentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	comment "github.com/edufriendchen/light-tiktok/kitex_gen/comment"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ActionComment(ctx context.Context, req *comment.ActionRequest, callOptions ...callopt.Option) (r *comment.ActionResponse, err error)
	MGetCommentList(ctx context.Context, req *comment.CommentRequest, callOptions ...callopt.Option) (r *comment.CommentResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) ActionComment(ctx context.Context, req *comment.ActionRequest, callOptions ...callopt.Option) (r *comment.ActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ActionComment(ctx, req)
}

func (p *kCommentServiceClient) MGetCommentList(ctx context.Context, req *comment.CommentRequest, callOptions ...callopt.Option) (r *comment.CommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MGetCommentList(ctx, req)
}
