package consts

const (
	TIKTOK_JSON           = "TIKTOK_JSON"
	DEFAULT_GROUP         = "DEFAULT_GROUP"
	API_SERVICE_NAME      = "api"
	API_SERVICE_ADDR      = ":1060"
	USER_SERVICE_NAME     = "user"
	USER_SERVICE_ADDR     = ":9000"
	RELATION_SERVICE_NAME = "relation"
	RELATION_SERVICE_ADDR = ":9100"
	MESSAGE_SERVICE_NAME  = "message"
	MESSAGE_SERVICE_ADDR  = ":9200"
	COMMENT_SERVICE_NAME  = "comment"
	COMMENT_SERVICE_ADDR  = ":9300"
	FAVORITE_SERVICE_NAME = "favorite"
	FAVORITE_SERVICE_ADDR = ":9400"
	FEED_SERVICE_NAME     = "feed"
	FEED_SERVICE_ADDR     = ":9500"
	PUBLISH_SERVICE_NAME  = "puslish"
	PUBLISH_SERVICE_ADDR  = ":9600"
)

const (
	DB_NEO4J_URI            = "db_neo4j_uri"
	DB_NEO4J_USERNAME       = "db_neo4j_username"
	DB_NEO4J_PASS           = "db_neo4j_password"
	NOTE_TABLE_NAME         = "note_table_name"
	USER_TABLE_NAME         = "user_table_name"
	SECRET_KEY              = "secret_key"
	IDENTITY_KEY            = "identity_key"
	TOTLE                   = "total"
	NOTES                   = "notes"
	MYSQL_DEFAULT_DSN       = "mysql_default_dsn"
	TCP                     = "tcp"
	EXPORT_ENDPOINT         = "export_endpoint"
	DEFAULT_LIMIT           = "default_limit"
	NACOS_ADDR              = "127.0.0.1"
	NACOS_POINT             = "nacos_point"
	NACOS_LOG_DIR           = "nacos_log_dir"
	NACOS_USERNAME          = "nacos"
	NACOS_PASSWORD          = "nacosfriend0429"
	JWT_SECRET_KEY          = "jwt_secret_key"
	LIMIT                   = "limit"
	MINIO_PREFIX            = "minio_prefix"
	MINIO_ENDPOINT          = "minio_endpoint"
	MINIO_ACCESS_KEY        = "minio_access_key_id"
	MINIO_SECRET_ACCESS_KEY = "minio_secret_access_key"
	MINIO_USER_SSL          = "minio_use_ssl"
	MINIO_BUCKET_NAME       = "minio_Bucket_name"
	START_TIME              = "start_time"
	CACHE_USER              = "user_cache:"
	CACHE_FEED              = "feed_cache:"
	CACHE_COMMENT           = "comment_cache:"
	CACHE_FAVORITE          = "favorite_cache;"
)
