// Code generated by Kitex v0.4.4. DO NOT EDIT.

package feedservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	feed "github.com/edufriendchen/light-tiktok/kitex_gen/feed"
)

func serviceInfo() *kitex.ServiceInfo {
	return feedServiceServiceInfo
}

var feedServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FeedService"
	handlerType := (*feed.FeedService)(nil)
	methods := map[string]kitex.MethodInfo{
		"MGetFeedList": kitex.NewMethodInfo(mGetFeedListHandler, newFeedServiceMGetFeedListArgs, newFeedServiceMGetFeedListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "feed",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func mGetFeedListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*feed.FeedServiceMGetFeedListArgs)
	realResult := result.(*feed.FeedServiceMGetFeedListResult)
	success, err := handler.(feed.FeedService).MGetFeedList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFeedServiceMGetFeedListArgs() interface{} {
	return feed.NewFeedServiceMGetFeedListArgs()
}

func newFeedServiceMGetFeedListResult() interface{} {
	return feed.NewFeedServiceMGetFeedListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) MGetFeedList(ctx context.Context, req *feed.FeedRequest) (r *feed.FeedResponse, err error) {
	var _args feed.FeedServiceMGetFeedListArgs
	_args.Req = req
	var _result feed.FeedServiceMGetFeedListResult
	if err = p.c.Call(ctx, "MGetFeedList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
