// Code generated by Validator v0.1.4. DO NOT EDIT.

package publish

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *ActionRequest) IsValid() error {
	return nil
}
func (p *ActionResponse) IsValid() error {
	return nil
}
func (p *PublishRequest) IsValid() error {
	return nil
}
func (p *PublishResponse) IsValid() error {
	return nil
}
